import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#695f00',
        'primary-container': '#ffeb3b',
        'primary-fixed': '#f9e534',
        'primary-fixed-dim': '#dbc90a',
        'on-primary': '#ffffff',
        'on-primary-container': '#746900',
        'on-primary-fixed': '#201c00',
        'on-primary-fixed-variant': '#4f4800',
        'inverse-primary': '#dbc90a',
        secondary: '#b51925',
        'secondary-container': '#d8363a',
        'secondary-fixed': '#ffdad7',
        'secondary-fixed-dim': '#ffb3ae',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#410004',
        'on-secondary-fixed-variant': '#930015',
        tertiary: '#0061a4',
        'tertiary-container': '#dceaff',
        'tertiary-fixed': '#d1e4ff',
        'tertiary-fixed-dim': '#9ecaff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#006bb4',
        'on-tertiary-fixed': '#001d36',
        'on-tertiary-fixed-variant': '#00497d',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#4a4733',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#7c7760',
        'outline-variant': '#cdc7ac',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        ink: '#000000',
        canvas: '#ffffff',
        action: '#FF5252',
        caution: '#FFEB3B',
        info: '#2196F3',
        'surface-tint': '#695f00',
      },
      fontFamily: {
        sans: ['var(--font-hanken-grotesk)', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
        'body-md': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'body-lg': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'headline-md': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'headline-lg': ['var(--font-hanken-grotesk)', 'sans-serif'],
        hero: ['var(--font-hanken-grotesk)', 'sans-serif'],
        'hero-mobile': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'label-mono': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '1.2', fontWeight: '800' }],
        'hero-mobile': ['40px', { lineHeight: '1.1', fontWeight: '800' }],
        hero: ['64px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'gap-xs': '4px',
        'gap-sm': '12px',
        'gap-md': '24px',
        'gap-lg': '48px',
        'margin-page': '24px',
        base: '8px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      boxShadow: {
        brutal: '4px 4px 0 0 #000000',
        'brutal-lg': '6px 6px 0 0 #000000',
        'brutal-hover': '6px 6px 0 0 #000000',
      },
    },
  },
  plugins: [],
};

export default config;
